<a href="https://colab.research.google.com/github/psrao123/50_days_of_data_analysis/blob/main/Day0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Day 0

In [ ]:
import numpy as np
lst = [1,2,3,4,5,6]
arr = np.array(lst, dtype=float)
arr

array([1., 2., 3., 4., 5., 6.])

In [ ]:
names = [['a','b','c'],['d','e','f']]
arr1 = np.array(names)
print(arr1)

[['a' 'b' 'c']
 ['d' 'e' 'f']]


In [ ]:
arr1.ndim

2

In [ ]:
arr2 = np.arange(0,50,5)
print(arr2)

[ 0  5 10 15 20 25 30 35 40 45]


In [ ]:
arr3 = np.zeros((2,3), dtype=float)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
rng = np.random.default_rng(seed=24)
rng.random((2,4) )

array([[0.33026884, 0.40517732, 0.57473782, 0.50639977],
       [0.56421251, 0.56968731, 0.87411653, 0.08643046]])

In [ ]:
arr1

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [ ]:
arr1[1,0:]

array(['d', 'e', 'f'], dtype='<U1')

In [ ]:
arr1[0,2]

np.str_('c')

In [ ]:
arr1[1,0]

np.str_('d')

In [ ]:
np.reshape(arr1, 6)

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [ ]:
np.concatenate([arr1,arr3], axis=1)

array([['a', 'b', 'c', '0.0', '0.0', '0.0'],
       ['d', 'e', 'f', '0.0', '0.0', '0.0']], dtype='<U32')

In [ ]:
arr1

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [ ]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.dot(arr1,arr2.transpose())

array([[ 140,  320],
       [ 320,  770],
       [ 500, 1220]])